[package]
name = "hello-world-rust"
version = "0.1.0"
authors = ["Simon Alexander Alsing (SAL) <sal@kamstrup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.2.0"
libbeaglebone = "0.5.0"